# Generated by Django 2.2.1 on 2019-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
            ],
        ),
    ]
